### ISSUE TITLE
config file 

### ISSUE THREAD

**Issue by BehdadSDP** [ajayshastry08/Parts-aware-DINO#1]
hello
I'm trying to evaluate the model and obtain the results that you have mentioned in your paper. 
I use this script  from pedestron for evaluate: 
`python ./tools/TEST_SCRIPT_TO_RUN.py PATH_TO_CONFIG_FILE ./models_pretrained/epoch_ start end\
 --out Output_filename --mean_teacher `
but I think the config file that you have mentioned in the repo it's not appropriate (maybe  I shouldn't use this config file for testing) because I get some attribute error that config file doesn't have them. 
thanks

**Comment by ajayshastry08** [comment]
Hello,

The command you've employed is not intended for our repository's program.

To initiate the evaluation process:
1. Execute the "main.py" program with the "--eval" flag.
2. Save the resulting bounding boxes in a CSV file.

After creating the CSV files for the datasets, utilize the appropriate evaluation script from the Pedestron repository designed for the respective datasets. These evaluation scripts are capable of accepting the generated CSV files as input.

**Comment by BehdadSDP** [comment]
thanks, I will check.
